apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: cite-generator
    image: yauritux/busybox-curl
    command: ["/bin/sh", "-c"]
    args:
    - >
      while true;
      do
        # Write two log files along with the date and a counter
        # every second
        # echo "$i: $(date)" >> /var/log/1.log;
        frase=$(curl -s https://dummyjson.com/quotes/random)
        echo $frase | grep -o '"quote":"[^"]*' | grep -o '[^"]*$'  >> /var/log/app.log;
        sleep 30;
      done
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: fluentd
    image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
    env:
      - name:  FLUENT_ELASTICSEARCH_HOST
        value: "136.119.119.232"
      - name:  FLUENT_ELASTICSEARCH_PORT
        value: "9200"
      - name: FLUENT_ELASTICSEARCH_SCHEME
        value: "http"
      - name: FLUENT_ELASTICSEARCH_USER
        value: "elastic"
      - name: FLUENT_ELASTICSEARCH_PASSWORD
        value: "changeme"
      - name: FLUENT_UID
        value: "0"
    resources:
      requests:
        memory: "200Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    volumeMounts:
    - name: varlog
      mountPath: /var/log
    - name: config-volume
      mountPath: /fluentd/etc
  volumes:
  - name: varlog
    emptyDir: {}
  - name: config-volume
    configMap:
      name: fluentd-config